# Generated by Django 3.0.5 on 2020-04-26 22:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editar_nav_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=20, null=True)),
                ('imagem_de_fundo', models.ImageField(null=True, upload_to='media/%Y/%m/%D')),
            ],
        ),
        migrations.CreateModel(
            name='FaleComigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeuBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, null=True)),
                ('fotos', models.ImageField(upload_to='media/%Y/%m/%D')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_curta', models.CharField(blank=True, max_length=300, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('educacao', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('interesse', models.TextField(blank=True, null=True)),
                ('imagem_sobre', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=10)),
                ('teste2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao_curta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição Curta')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/posts/%Y/%m/%D', verbose_name='Foto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
