# Generated by Django 3.0.5 on 2020-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(blank=True, choices=[('HTML/CSS', 'HTML/CSS'), ('Js', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django'), ('Bootstrap', 'Bootstrap'), ('Conteúdo Região', 'Conteudo Região')], max_length=15, null=True, verbose_name='Tipo de Postagem'),
        ),
    ]
