# Generated by Django 2.0.13 on 2019-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('nome_do_produto', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('codigo_compra', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('codigo_petshop', models.IntegerField(primary_key=True, serialize=False)),
                ('atendente', models.CharField(max_length=50)),
            ],
        ),
    ]
