# Generated by Django 2.2.1 on 2019-09-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190917_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editar_nav_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=20)),
                ('item1', models.CharField(max_length=20)),
                ('item2', models.CharField(max_length=20)),
                ('item3', models.CharField(max_length=20)),
                ('imagem_de_fundo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D')),
            ],
        ),
    ]
