# Generated by Django 2.2.1 on 2019-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_editar_nav_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts/%Y/%m/%D'),
        ),
    ]
