# Generated by Django 2.2.1 on 2019-09-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editar_nav_blog',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='editar_nav_blog',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='editar_nav_blog',
            name='item3',
        ),
    ]
