# Generated by Django 2.2.1 on 2019-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190918_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField()),
                ('imagem_sobre', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D')),
            ],
        ),
    ]
