# Generated by Django 2.2.1 on 2019-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_falecomigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremim',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
