# Generated by Django 2.2.1 on 2019-09-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_sobremim_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
