# Generated by Django 2.2.1 on 2019-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190927_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=10)),
                ('teste2', models.IntegerField()),
            ],
        ),
    ]
