# Generated by Django 2.2.1 on 2019-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
