# Generated by Django 2.1.2 on 2019-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_servicomanutencao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobremim',
            old_name='nome',
            new_name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='sobremim',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='sobremim',
            name='sobre',
        ),
        migrations.AddField(
            model_name='sobremim',
            name='educacao',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='experiencia',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='habilidades',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='interesse',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
