# Generated by Django 2.1.2 on 2019-10-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191001_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
