# Generated by Django 2.1.2 on 2019-10-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_sobremim_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremim',
            name='educacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='interesse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
