# Generated by Django 2.1.2 on 2019-10-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191001_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremim',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
