# Generated by Django 2.1.2 on 2019-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_meublog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meublog',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
