# Generated by Django 2.1.2 on 2019-10-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_meublog_descricao_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meublog',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
